config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#top'
  get 'home/about' => "users#about"
  resources :users, only: [:new, :create, :index, :show, :edit, :update] do
  		get :about, on: :collection
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :title, length: { maximum: 200 }
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  def after_sign_out_path_for(resource)
    root_path
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_book, only: [:edit, :update]

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
	end

	def create
		@book = Book.new(book_params)
		@book = current_user.books.new(book_params)
		if @book.save
		   redirect_to book_path(@book.id), notice: "You have creatad book successfully."
		else
			@books = Book.all
			@user = current_user
			render 'index'
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   redirect_to book_path(@book.id), notice: "You have updated book successfully."
		else
		   render 'edit'
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
		def book_params
		 params.require(:book).permit(:title, :body)
		end

		def correct_book
			@book = Book.find(params[:id])
			if @book.id != current_user.id
			   redirect_to books_path
			end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!, only: [:show, :new, :index, :edit]
    before_action :correct_user, only: [:edit, :update]

    def new
		@user = User.new
    end
    def create
    	@user = User.new(user_params)
    	@user.user_id = current_user.user_id
    	if @user.save
    	   redirect_to users_path
        else
            render 'index'
        end
    end
    def index
        @user = current_user
        @users = User.all
        @book = Book.new
        @books = Book.all
    end
    def show
        @book = Book.new
        @books = Book.all
        @user = User.find(params[:id])
        @users = User.all
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
           redirect_to user_path(@user.id), notice: "You have updated user successfully."
        else
           render 'edit'
        end
    end

    private
    	def user_params
    		params.require(:user).permit(:name, :profile_image, :introduction)
    	end

        def correct_user
            @user = User.find(params[:id])
            if @user.id != current_user.id
               redirect_to user_path(current_user.id)
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
  </head>

  <body>

  <div class='container'>
  	

    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>

      	<h1>Editing Book</h1>

        <% if @book.errors.any? %>
          <h4>Input error:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

      	<%= form_for(@book) do |f| %>

          <div class="field row">
          <h4>Title</h4>
      		<%= f.text_field :title %>
          </div>

          <div class="field row">
          <h4>Body</h4>
      		<%= f.text_area :body %>
          </div>

          <div class="actions row">
      		<%= f.submit 'Update Book' %>
          </div>

      	<% end %>

      </div>
    </div>
  
    <div class="actions row">
      <div class='col-md-6 col-md-offset-3'>
    	<%=link_to "Show", book_path %>
    	<%=link_to "Back", books_path %>
      </div>
    </div>

  </div>

  </body>

  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>
    

  	<div class='body'>
<div class='container'>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

  <div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag current_user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "100x100" %></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= current_user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= current_user.introduction %></th>
      </tr>
    </table>

    

    <div class='row'>
      <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
    </div>

    <h2>New book</h2>

        <% if @book.errors.any? %>
          <h4>Input error:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
    
    <%= form_for(@book) do |f| %>
      
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Body</h4>
      <%= f.text_area :body %>

      <%= f.submit 'Create Book' %>

    <% end %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <table class='table table-hover table-inverse'>
      <thead>
        <tr> 
          <th></th>
          <th>title</th>
          <th>opinion</th>
          <th></th>
        </tr>
      </thead>

      <% @books.each do |book| %>

        <tbody>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "60x60" %></td>
              <td><%= link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
        </tbody>

      <% end %>

    </table>
  </div>

      </div>
</div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/books/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

<div class='body'>
<div class='container'>

        <p id="notice">Signed in successfully.</p>


  <div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag @user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "100x100" %></tr> 
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </table>
    <%= link_to "プロフィール編集", new_user_path %>


    <div class='row'>
      <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9814" href="/users/9814/edit"></a>
    </div>

    <h2>New book</h2>
    
    <%= form_for(@book) do |f| %>
      
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Body</h4>
      <%= f.text_area :body %>

      <%= f.submit 'Create Book' %>

    <% end %>

  </div>

    <div class='col-xs-9'>
      <h2>Book Detail</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr> 
            <th></th>
            <th>title</th>
            <th>opinion</th>
            <th></th>
          </tr>
        </thead>


        <tbody>
            <tr>
              <td><a href="/users/9814">
                <img class="attachment user profile_image" src="/attachments/2ed7c4c6b203429ce5675039a44992f08b29efb0/store/fill/50/50/05c8a04fdcd571d14f8bcda6ab316f5da0dbc739a68ccd63025d39eb911a/profile_image" alt="Profile image" /></a></td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <td><%=link_to "Edit",edit_book_path(@book.id) %></td>
              <td><%= link_to "Destroy", book_path, method: :delete %>
            </tr>
        </tbody>

      </table>
    </div>
  </div>
</div>
</div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

<div class='body'>
<div class='container'>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

  <div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "100x100" %></tr> 
      <tr>
        <th>name</th>
        <th><%= @book.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @book.user.introduction %></th>
      </tr>
    </table>
    
    <div class='row'>
      <% if @book.user.id == current_user.id %>
        <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <% else %>
        <p><%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <% end %>
    </div>

    <h2>New book</h2>
    
    <%= form_for(@book) do |f| %>
      
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Body</h4>
      <%= f.text_area :body %>

      <%= f.submit 'Create Book' %>

    <% end %>

  </div>

    <div class='col-xs-9'>
      <h2>Book Detail</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr> 
            <th></th>
            <th>title</th>
            <th>opinion</th>
            <th></th>
          </tr>
        </thead>


        <tbody>
            <tr>
              <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "60x60" %>
                <br><%= link_to "#{@book.user.name}", user_path(@book.user.id) %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <% if @book.user.id == current_user.id %>
                <td><%=link_to "Edit",edit_book_path(@book.id) %></td>
                <td><%= link_to "Destroy", book_path, method: :delete %>
              <% end %>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
            </tr>
        </tbody>

      </table>
    </div>
  </div>
</div>
</div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left'>
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Home", user_path(current_user.id), :class => "glyphicon glyphicon-home" %>
              </li>
              <li>
                <%= link_to "Users", users_path, :class => "glyphicon glyphicon-user" %>
              </li>
              <li>
                <%= link_to "Books", books_path, :class => "glyphicon glyphicon-book" %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, :class => "glyphicon glyphicon-log-out" %>
              </li>
            <% else %>
              <li>
                <%= link_to "Home", root_path, :class => "glyphicon glyphicon-home" %>
              </li>
              <li>
                <%= link_to "About", home_about_path, :class => "glyphicon glyphicon-link" %>
              </li>
              <li>
                <%= link_to "Sign up", new_user_registration_path, :class => "glyphicon glyphicon-edit" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, :class => "glyphicon glyphicon-log-in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>
    

  	<div class='body'>
      <div class='container'>
        <div class='row'>
      	   <h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>
        </div>
      </div>
    </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

  	<div class='body'>
      <div class='container'>



      	<h2>User info</h2>

        <% if @user.errors.any? %>
          <h4>Input error:</h4>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_for(@user) do |f| %>

          <div class="field">
            <label for="user_name">Name</label>
            <%= f.text_field :name, class:"form-control", placeholder:"ユーザ名" %>
            <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
          </div>

          <div class="field">
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image %>
          </div>

          <div class="field">
            <label for="user_introduction">Introduction</label>
            <%= f.text_field :introduction, class:"form-control", placeholder:"本文" %>
            <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
          </div>

          <div class="actions">
            <%= f.submit "Update User" %>
          </div>
        <% end %>
      </div>
    </div>

    <footer>
      <div class='container'>
      	<div class='row'>
        	<div class='col-xs-3 col-xs-offset-9'>
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

  <div class='container'>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>


    <div class='row'>
  
      <div class='col-xs-3'>
        <h2>User info</h2>
        <table class='table'>
          <tr><%= attachment_image_tag current_user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "100x100" %></tr> 
          <tr>
        	  <th>name</th>
        	  <th><%= current_user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= current_user.introduction %></th>
          </tr>
        </table>


        <div class='row'>
          <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
        </div>

        <h2>New book</h2>

        <%= form_for(@book) do |f| %>

          <% if @book.errors.any? %>
            <h4>Input error:</h4>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>

          <h4>Title</h4>
          <%= f.text_field :title %>

            <h4>Body</h4>
            <%= f.text_area :body %>

            <%= f.submit 'Create Book' %>

        <% end %>

      </div>

      <div class='col-xs-9'>
        <h2>Users</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr> 
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>

          <% @users.each do |user| %>

            <tbody>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "60x60" %></td>
                  <td><%= user.name %></td>
                  <td><%= link_to "Show", user_path(user.id) %></td>
                </tr>
            </tbody>

          <% end %>

        </table>
      </div>

    </div>
  </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

  	<div class='body'>
      <div class='container'>



      	<h2>User info</h2>

<%= form_for(@user) do |f| %>

  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name, class:"form-control", placeholder:"ユーザ名" %>
    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
  </div>

  <div class="field">
    <label for="user_image">Image</label>
    <%= f.attachment_field :profile_image %>
  </div>

  <div class="field">
    <label for="user_introduction">Introduction</label>
    <%= f.text_field :introduction, class:"form-control", placeholder:"本文" %>
    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
  </div>

  <div class="actions">
    <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  </div>
<% end %>
      </div>
    </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>

  	<div class='body'>
<div class='container'>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

  <div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag @user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "100x100" %></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= @user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= @user.introduction %></th>
      </tr>
    </table>

    

    <div class='row'>
      <% if @user.id == current_user.id %>
        <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <% else %>
        <p><%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <% end %>
    </div>

    <h2>New book</h2>

        <% if @book.errors.any? %>
          <h4>Errors:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
    
    <%= form_for(@book) do |f| %>
      
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Body</h4>
      <%= f.text_area :body %>

      <%= f.submit 'Create Book' %>

    <% end %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <table class='table table-hover table-inverse'>
      <thead>
        <tr> 
          <th></th>
          <th>title</th>
          <th>opinion</th>
          <th></th>
        </tr>
      </thead>

      <% @books.each do |book| %>

        <tbody>
          <% if book.user == @user %>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", size: "60x60" %></td>
              <td><%= link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      <% end %>

    </table>
  </div>

      </div>
</div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>


  </body>
</html>

app/views/users/top.html.erb
    

  	<div class='body'>
      <div class='container'>

        <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
        <% end %>

      	<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
         <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
            
  </div>
</div>
        

      </div>
    </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>